# Generated by Django 5.2.2 on 2025-06-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
